services:
  app:
    image: express-authen/node:v1
    environment:
      - DB_CONNECT=${DB_CONNECT} # Kết nối tới MongoDB service
      - PORT=${PORT}
      - DOKER_PORT=${DOKER_PORT}
    ports:
      - "${PORT}:${DOKER_PORT}"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
