version: "3.7"

services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - mynetwork

  app:
    image: express-authen/node:v1
    container_name: node-app
    environment:
      - DB_CONNECT=mongodb://mongo:27017/mydatabase
      - PORT=3005
      - DOKER_PORT=3005
    ports:
      - "3005:3005"
    depends_on:
      - mongo
    networks:
      - mynetwork

  mongo:
    image: mongo:latest
    container_name: mongo-container
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork

volumes:
  mongo-data:
    driver: local

networks:
  mynetwork:
    driver: bridge
